.Net7 and integration tests
AnalogIO/analog-core pull request #191
Opened 2023-07-25 17:33 UTC by TTA777

- Upgraded to .Net7
- Added a new project containing builders for our entities, which should ease the writing of tests
- Added a shared setup for our integration tests
- Added a few integration tests to demonstrate the new setup

The upgrade to .net7 was a bit "quick and dirt" in that I haven't tested everything with it yet, which is why I marked the PR as draft.

The implementation of the builders is also something we may want to discuss

2023-08-15 18:45 UTC, TTA777 commented
Notes from meeting today:
- Needs to add seed to autofaker, to ensure test will be deterministic
- Update docker/ infra code to account for dotnet 7 instead
- Updating the current unit tests with the builders is outside the scope of this PR
- Long term, we want to investigate the possibility of adding a strongly typed, generated http client to the integration tests as well

2023-11-09 16:48 UTC, duckth requested changes
Remember to update DOTNET_VERSION constant in core-build.yml

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.Library/CoffeeCard.Library.csproj
> +    <LangVersion>8</LangVersion>
```suggestion
    <LangVersion>default</LangVersion>
```

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.MobilePay.GenerateApi/CoffeeCard.MobilePay.GenerateApi.csproj
> +    <LangVersion>8</LangVersion>
```suggestion
    <LangVersion>default</LangVersion>
```

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.Tests.Common/Builders/StatisticBuilder.cs
> +                .WithUser(user); ;
An extra semicolon..? Or weird formatting?

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.Tests.Integration/CoffeeCard.Tests.Integration.csproj
>      <LangVersion>8</LangVersion>
```suggestion
    <LangVersion>default</LangVersion>
```

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.Tests.Unit/CoffeeCard.Tests.Unit.csproj
>      <LangVersion>8</LangVersion>
```suggestion
    <LangVersion>default</LangVersion>
```

2023-11-09 16:48 UTC, duckth commented on coffeecard/CoffeeCard.WebApi/CoffeeCard.WebApi.csproj
>      <LangVersion>8</LangVersion>
```suggestion
    <LangVersion>default</LangVersion>
```

2024-02-13 19:01 UTC, duckth approved these changes

2024-02-13 19:02 UTC, merged