First draft on a released based deployment workflow
AnalogIO/analog-core pull request #213
Opened 2023-09-23 20:46 UTC by jonasanker

2023-10-30 18:19 UTC, duckth requested changes

2023-10-30 18:19 UTC, duckth commented on .github/workflows/deploy-dev.yml
> +name: Deploy to dev
Minor, but the indentation seems off in this file (4 spaces) - other files seem to use 2 spaces so let's be consistent

2023-10-30 18:19 UTC, duckth commented on .github/workflows/deploy-prd.yml
> +name: Deploy to prd
ditto

2023-10-30 18:19 UTC, duckth commented on .github/workflows/pullrequest.yml
> +name: Pull Request
also here

2023-11-02 00:01 UTC, jonasanker commented
@duckth I can make the identation changes next week but if you are bored tomorrow, feel free to perform the changes yourself and merge this PR :)

2023-11-02 05:38 UTC, duckth commented
> @duckth I can make the identation changes next week but if you are bored tomorrow, feel free to perform the changes yourself and merge this PR :)

Sure thing, I'll do it 👍

2023-11-02 15:38 UTC, duckth approved these changes

2023-11-12 22:06 UTC, merged