feat: adds ticket status (refunded) & adds refund logic
AnalogIO/analog-core pull request #287
Opened 2024-10-01 16:51 UTC by marfavi

- Tickets are now marked as refunded when calling `PurchaseService.RefundPurchase`.

- Enhanced refund logic to ensure only fully unused purchases are refundable.

- Replaced the boolean `IsUsed` property with a `Status` property on tickets to better represent 3 states (unused, used, refunded).

- Added `IsUsed` and `IsUnused` read-only convenience properties to Ticket.

- Improved method clarity by renaming operations related to unused tickets.

2024-10-01 17:35 UTC, TTA777 requested changes

2024-10-01 17:35 UTC, TTA777 commented on coffeecard/CoffeeCard.Models/Entities/Ticket.cs
> -        public bool IsUsed { get; set; }
On second thought, I think we should play this safe and not delete anything until. Mark it as obsolete (true) for now. That way, nothing can reference it without breaking the build, but we preserve the data

2024-10-02 08:53 UTC, marfavi commented
I have no idea why build fails. Seems like some generated files still attempt to access the obsolete `IsUsed` field @TTA777

2024-10-02 11:13 UTC, TTA777 commented
@marfavi Yeah, that would be my fancy source generator for builders we use for writing the integration tests. They don't account for properties being obsolete. I can push a fix for it later

2024-10-08 16:16 UTC, TTA777 submitted a review, later dismissed
Ship it

2024-10-08 16:26 UTC, TTA777 approved these changes
Ship it now

2024-10-08 16:26 UTC, merged