Feature/user purchases
AnalogIO/analog-core pull request #288
Opened 2024-10-08 18:21 UTC by fredpetersen

2024-10-09 11:49 UTC, marfavi approved these changes
Looks good to me

2024-10-22 14:15 UTC, TTA777 requested changes

2024-10-22 14:15 UTC, TTA777 commented on coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs
> +                Log.Error("No user was found by User Id: {Id}", userId);
Use structured logging, not string interpolation

2024-10-22 14:17 UTC, TTA777 approved these changes

2024-10-22 14:25 UTC, merged