Feature/fremartini/add userid to log
AnalogIO/analog-core pull request #44
Opened 2021-11-16 20:05 UTC by fremartini

closing #41

2021-11-19 20:24 UTC, jonasanker requested changes
Overall looks good. I have added some changes I think you should address

2021-11-19 20:24 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Logging/Enrichers/UserIdEnricher.cs
> +            var id = claims.Count > 2 ? claims[2].Value : "NONE";
It seems a bit vulnerable to rely on a specific index to retrieve the UserId. I suggest using
```suggestion
            var id =  _contextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier);
```
See ref [What is the way in ASP.NET Core 3.0 to get current authenticated User username?](https://stackoverflow.com/questions/58473739/what-is-the-way-in-asp-net-core-3-0-to-get-current-authenticated-user-username)

2021-11-19 20:24 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Logging/Enrichers/UserIdEnricher.cs
> +            return $"userid:{id}";
It would be better to not add the enricher in the log statement if no user is logged in, rather than adding `NONE`. Is that possible?

2021-11-19 20:24 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Logging/Enrichers/UserIdEnricher.cs
> +        }
Do you know if we can just use Dependency Injection? I can see you are just following the pattern from `CorrelationIdEnricher` but wondering if below shouldn't be possible:

```suggestion
        public UserIdEnricher(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor;
        }
```

2021-11-22 21:41 UTC, fremartini commented
@jonasanker considered and implemented proposed changes

2021-11-23 17:27 UTC, jonasanker approved these changes
Approved with latest changes

2021-11-23 17:32 UTC, merged