add endpoint to check if email is already registered
AnalogIO/analog-core pull request #78
Opened 2022-03-27 12:12 UTC by fremartini

closes #67

2022-03-27 12:25 UTC, jonasanker requested changes
Changes Requested

2022-03-27 12:25 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        [HttpPost]
The endpoint should be anonymous
```csharp
[AllowAnonymous]
```

2022-03-27 12:25 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        public async Task<ActionResult<EmailInUseDTO>> EmailInUse([FromBody] string email)
- Input should be an object
- Document parameter in above code comments

2022-03-27 12:25 UTC, jonasanker commented on coffeecard/CoffeeCard.Models/DataTransferObjects/User/EmailInUseDTO.cs
> +    public class EmailInUseDTO
1) Shold be added to the v2 subfolder
2) In Api V2, we tend to not the the DTO suffix but instead give a more direct name, e.g. `EmailInUseResponse`

2022-03-27 12:25 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        [Route("emailinuse")]
In Rest, we usually name the action with a verb. This is understood as we _apply_ an action on the REST collection. With that in mind, I would like to find another name than _emailInUse_. 

Suggestions
- `/check-email`
- `/check-duplicate-email`

2022-03-27 14:08 UTC, jonasanker requested changes

2022-03-27 14:08 UTC, jonasanker commented on coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/EmailInUseRequest.cs
> +    ///     "email": "johndoe@mail.com",
No comma here

2022-03-27 14:08 UTC, jonasanker commented on coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/EmailInUseResponse.cs
> +    ///     "InUse": true,
No comma

2022-03-27 14:08 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        [Route("check-email-in-use")]
I think _email in use_ is a bit clumsy name compared to e.g. email exists

2022-03-27 14:08 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        public async Task<ActionResult<EmailInUseResponse>> EmailInUse([FromBody] EmailInUseRequest request)
We should add code documentation for this parameter

2022-03-27 14:08 UTC, jonasanker commented on coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/EmailInUseResponse.cs
> +        public bool InUse { get; set; }
Suggestion: Email exists

2022-03-27 21:21 UTC, jonasanker requested changes

2022-03-27 21:21 UTC, jonasanker commented on coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
> +        public async Task<ActionResult<EmailInUseResponse>> EmailInUse([FromBody] EmailInUseRequest request)
With the update route value, the method name should be updated to align. Same goes with request and response class name 😉

2022-03-28 11:04 UTC, jonasanker requested changes

2022-03-28 11:10 UTC, jonasanker requested changes

2022-03-28 11:17 UTC, fremartini commented on coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/EmailExistsResponse.cs
> +    ///     "EmailExists": true
it already is? EmailExists?

2022-04-05 17:47 UTC, jonasanker commented on coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/EmailExistsResponse.cs
> +    ///     "EmailExists": true
It's not in the example

2022-04-05 21:02 UTC, jonasanker approved these changes

2022-04-06 05:16 UTC, merged